### ISSUE TITLE
Set `isolatedDeclarations` to `true` and `skipLibCheck` to `false`.

### ISSUE THREAD

**Issue by carlansley** [checkdigit/typescript-config#63]
Requires Typescript 5.6, once it has been released.

**Comment by le-cong** [comment]
one blocking issue preventing us from setting `skipLibCheck` to `false` is due to [an incorrect typing entry in antlr4's package.json](https://github.com/antlr/antlr4/issues/4662). the good news is that this issue has been fixed in `antlr4 v4.13.2`. 
it looks promising to be able to disable `skipLibCheck` again with this issue out of the way.
